import type { Metadata } from 'next'
import '@mantine/core/styles.css'
import './globals.css'
import { ColorSchemeScript, Stack } from '@mantine/core'
import { AppProvider } from './provider'
import { AppHeader } from '@/components/AppHeader'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <AppProvider>
          <Stack component="section" mih="100vh" gap={0}>
            <AppHeader />
            {children}
          </Stack>
        </AppProvider>
      </body>
    </html>
  )
}
